version: "3.8"

services:
  bun_backend:
    container_name: bun_backend
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    networks:
      - bun-network
    env_file:
      - .env
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-development}
      - DATABASE_URL=${DATABASE_URL}

  bun_frontend:
    container_name: bun_frontend
    ports:
      - "${PORT:-80}:80"
    build:
      context: .
      dockerfile: docker/Dockerfile.react
    networks:
      - bun-network
    depends_on:
      - bun_backend
    env_file:
      - .env
    environment:
      - SITE_DOMAIN=${SITE_DOMAIN}
      - NODE_ENV=${NODE_ENV:-development}

networks:
  bun-network:
    driver: bridge
